
@endpoint = https://c1v2xozat1.execute-api.ca-central-1.amazonaws.com/prod/

GET {{endpoint}}/hello
###

GET {{endpoint}}/readLambda/?search=reservation&creteria=somecreteria
###

GET {{endpoint}}/createTable
###