
@endpoint = https://hkawz53qd0.execute-api.us-east-1.amazonaws.com/prod/

@SearchFlowApiEndpoint = https://33ye23ukr3.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/hello
###

GET {{endpoint}}/readLambda/?search=reservation&creteria=somecreteria
###

GET {{endpoint}}/create-table
###

GET {{endpoint}}/read
###

PUT {{endpoint}}/update/5
Content-Type: application/json

{
  "arrival_date": "2023-11-18",
  "departure_date": "2023-11-20",
  "room_size": "business-suit",
  "room_quantity": 4,
  "first_name": "John",
  "last_name": "Doe",
  "email": "johndoe@example.com",
  "phone": "1234567890",
  "street_name": "Main St",
  "street_number": "123",
  "zip_code": "12345",
  "state": "CA",
  "city": "San Francisco",
  "extras": "extraBreakfast",
  "payment": "cc",
  "note": "high floor",
  "tags": "business",
  "reminder": false,
  "newsletter": false,
  "confirm": true
}
###

POST {{endpoint}}/new-create/
Content-Type: application/json

{
  "arrival_date": "2023-11-18",
  "departure_date": "2023-11-20",
  "room_size": "business-suit",
  "room_quantity": 4,
  "first_name": "Jhon",
  "last_name": "Snow",
  "email": "johnsnow@example.com",
  "phone": "1234567890",
  "street_name": "Main St",
  "street_number": "123",
  "zip_code": "12345",
  "state": "CA",
  "city": "San Francisco",
  "extras": "extraBreakfast",
  "payment": "cc",
  "note": "high floor",
  "tags": "business",
  "reminder": false,
  "newsletter": false,
  "confirm": true
}
###

DELETE {{endpoint}}/delete?id=2
###

GET {{SearchFlowApiEndpoint}}/search/?search=Los&criteria=city
###
GET {{SearchFlowApiEndpoint}}/search/?search=bob&criteria=email
###

GET {{SearchFlowApiEndpoint}}/search/?search=ali&criteria=firstName
###

GET {{SearchFlowApiEndpoint}}/search/?search=jo&criteria=lastName
###