
@endpoint = https://hkawz53qd0.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/hello
###

GET {{endpoint}}/readLambda/?search=reservation&creteria=somecreteria
###

GET {{endpoint}}/create-table
###